@startuml idp
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Ext(provider, "Externl Identity Provider", "i. e. Google, Apple, using for OAuth flow")
@enduml
