@startuml idp
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(spa, "Single Page Application", "React", "Give access to user and admin features")
@enduml
